job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git("https://github.com/Varundwivedi410/sample.git", 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'maven-samples/single-module/pom.xml')
    }
    publishers {
        //archive the war file generated
<<<<<<< HEAD
        archiveArtifacts '**/*.jar'
=======
        archiveArtifacts('**/*.jar')
>>>>>>> db89cb9c867cfa61c1b9f70415df5c24b186d4ff
    }
}
